# Generated by Django 5.0.1 on 2024-02-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
    ]
